<?php

/**
 * @file
 * Contains webform element hook implementations.
 */

/**
 * Implements hook_openid_connect_claims_alter().
 */
function os2forms_organisation_bruger_id_openid_connect_claims_alter(array &$claims) {
  $claims['organisation_user_id'] = [
    'scope' => 'profile',
    'title' => 'Organisations user ID',
    'type' => 'string',
    'description' => 'SF1500 user ID',
  ];
}

/**
 * Implements hook_openid_connect_userinfo_alter().
 */
function os2forms_organisation_bruger_id_openid_connect_userinfo_alter(array &$userinfo, array $context) {
  // SF1500 Organisation bruger ID.
  // @see https://digitaliseringskataloget.dk/integration/sf1500
  if (!isset($userinfo['organisation_user_id']) && isset($userinfo['nameidentifier'])) {
    $userinfo['organisation_user_id'] = $userinfo['nameidentifier'];
  }
}
